Repository replugged-org/replugged, pull requests merged in 2023-04, with the labels that each got.

#441 fix: Switch component
  src/renderer/modules/common/guilds.ts
  src/renderer/modules/components/CheckboxItem.tsx
  src/renderer/modules/components/SwitchItem.tsx
Labels: semver: patch

#447 fix: fluxdispatcher broken by discord updates
  src/renderer/modules/common/api.ts
  src/renderer/modules/common/channels.ts
  src/renderer/modules/common/flux.ts
  src/renderer/modules/common/fluxDispatcher.ts
  src/renderer/modules/common/guilds.ts
  src/renderer/modules/common/hljs.ts
  src/renderer/modules/common/i18n.ts
  src/renderer/modules/common/lodash.ts
  src/renderer/modules/common/messages.ts
  src/renderer/modules/common/parser.ts
  src/renderer/modules/common/react-dom.ts
  src/renderer/modules/common/react.ts
  src/renderer/modules/common/typing.ts
  src/renderer/modules/common/users.ts
  src/types/webpack.ts
Labels: bug, semver: patch

#445 fix: language coremod plaintext patch
  src/renderer/coremods/language/plaintextPatches.ts
Labels: bug, semver: patch

#448 fix(badges): crash due to Discord changes
  src/renderer/coremods/badges/index.tsx
Labels: bug, semver: patch

#452 feat(badges): change module, add sizes and memoize current cache
  package.json
  pnpm-lock.yaml
  src/renderer/coremods/badges/badge.tsx
  src/renderer/coremods/badges/badges/Booster.tsx
  src/renderer/coremods/badges/badges/BugHunter.tsx
  src/renderer/coremods/badges/badges/Contributor.tsx
  src/renderer/coremods/badges/badges/Developer.tsx
  src/renderer/coremods/badges/badges/EarlyUser.tsx
  src/renderer/coremods/badges/badges/Staff.tsx
  src/renderer/coremods/badges/badges/Support.tsx
  src/renderer/coremods/badges/badges/Translator.tsx
  src/renderer/coremods/badges/index.tsx
  src/renderer/modules/common/channels.ts
  src/renderer/modules/common/users.ts
Labels: bug, semver: patch, types
