Repository replugged-org/replugged, pull requests merged in 2023-08, with the labels that each got.

#515 Addon embeds
  cspell.json
  i18n/cs.json
  i18n/de.json
  i18n/en-GB.json
  i18n/en-US.json
  i18n/es-ES.json
  i18n/fi.json
  i18n/fr.json
  i18n/it.json
  i18n/ms.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/sk.json
  src/globals.d.ts
  src/renderer/coremods/installer/AddonEmbed.tsx
  src/renderer/coremods/installer/addonEmbed.css
  src/renderer/coremods/installer/index.tsx
  src/renderer/coremods/installer/util.tsx
  src/renderer/coremods/settings/pages/General.tsx
  src/renderer/coremods/settings/pages/QuickCSS.tsx
  src/types/settings.ts
Labels: enhancement, semver: minor

#509 feat: add React DevTools
  i18n/en-GB.json
  i18n/fi.json
  i18n/it.json
  i18n/pl.json
  package.json
  pnpm-lock.yaml
  src/main/index.ts
  src/main/ipc/index.ts
  src/main/ipc/installer.ts
  src/main/ipc/react-devtools.ts
  src/main/ipc/settings.ts
  src/preload.ts
  src/renderer/coremods/settings/pages/General.tsx
  src/renderer/modules/common/flux.ts
  src/renderer/modules/common/fluxDispatcher.ts
  src/renderer/modules/common/messages.ts
  src/types/index.ts
  src/types/settings.ts
  src/util.mts
Labels: enhancement, semver: minor

#527 Context menu API fix
  cspell.json
  src/renderer/coremods/contextMenu/index.tsx
  src/renderer/modules/injector.ts
Labels: bug, semver: patch

#529 Fix experiments patch
  src/renderer/coremods/experiments/plaintextPatches.ts
Labels: bug, semver: patch

#530 Addon version release command
  bin/release.mjs
  bin/replugged.mjs
  cspell.json
  package.json
  pnpm-lock.yaml
Labels: semver: minor, addon development

#533 Add workaround for quickcss/main.css ownership
  src/util.mts
Labels: bug, semver: patch

#534 Better implementation of useStateFromStoresArray and useStateFromStoresObject
  src/renderer/modules/common/flux.ts
  src/renderer/modules/common/messages.ts
  src/types/coremods/contextMenu.ts
Labels: bug, semver: patch, types

#532 Track install type and version
  src/main/ipc/installer.ts
  src/preload.ts
  src/renderer/coremods/installer/util.tsx
  src/renderer/managers/updater.ts
Labels: enhancement, semver: patch

#537 Update fluxDispatcher.ts
  src/renderer/modules/common/fluxDispatcher.ts
Labels: semver: patch, types

#539 Install embed fixes
  src/renderer/coremods/installer/index.tsx
  src/renderer/coremods/installer/util.tsx
Labels: bug, semver: patch

#545 Fix install warning for un-reviewed addon
  src/renderer/coremods/installer/util.tsx
Labels: bug, semver: patch

#544 fix: addon embed authors overflow
  src/renderer/coremods/installer/AddonEmbed.tsx
  src/renderer/coremods/installer/addonEmbed.css
Labels: bug, semver: patch
