Repository replugged-org/replugged, pull requests merged in 2023-05, with the labels that each got.

#459 Support NodeJS v20 for scripts
  .eslintrc.yml
  package.json
  scripts/build.mts
  scripts/inject/checks/elevate.mts
  scripts/inject/checks/env.mts
  scripts/inject/index.mts
  scripts/inject/injector.mts
  scripts/inject/platforms/darwin.mts
  scripts/inject/platforms/linux.mts
  scripts/inject/platforms/win32.mts
  scripts/inject/types.mts
  scripts/inject/util.mts
  src/main/index.ts
  src/main/ipc/installer.ts
  src/main/ipc/plugins.ts
  src/main/ipc/quick-css.ts
  src/main/ipc/settings.ts
  src/main/ipc/themes.ts
  src/renderer/coremods/settings/pages/Updater.tsx
  src/util.mts
Labels: bug, semver: none

#453 feat(main): Replace `x-frame-options` header in favor of `frame-ancestors`
  src/main/index.ts
Labels: semver: minor

#454 findInTree and findInReactTree utils
  cspell.json
  src/renderer/util.ts
Labels: enhancement, semver: minor

#461 feat(types): modules completion and improvement
  cspell.json
  package.json
  pnpm-lock.yaml
  src/renderer/coremods/installer/index.tsx
  src/renderer/coremods/settings/pages/codemirror-github.ts
  src/renderer/modules/common/api.ts
  src/renderer/modules/common/channels.ts
  src/renderer/modules/common/constants.ts
  src/renderer/modules/common/contextMenu.ts
  src/renderer/modules/common/flux.ts
  src/renderer/modules/common/fluxDispatcher.ts
  src/renderer/modules/common/guilds.ts
  src/renderer/modules/common/i18n.ts
  src/renderer/modules/common/index.ts
  src/renderer/modules/common/messages.ts
  src/renderer/modules/common/modal.ts
  src/renderer/modules/common/parser.ts
  src/renderer/modules/common/toast.ts
  src/renderer/modules/common/users.ts
  src/renderer/modules/components/ButtonItem.tsx
  src/renderer/modules/components/CheckboxItem.tsx
  src/renderer/modules/components/Clickable.tsx
  src/renderer/modules/components/ContextMenu.tsx
  src/renderer/modules/components/Divider.tsx
  src/renderer/modules/components/Flex.tsx
  src/renderer/modules/components/FormItem.tsx
  src/renderer/modules/components/FormNotice.tsx
  src/renderer/modules/components/FormText.tsx
  src/renderer/modules/components/Loader.tsx
  src/renderer/modules/components/Notice.tsx
  src/renderer/modules/components/RadioItem.tsx
  src/renderer/modules/components/SelectItem.tsx
  src/renderer/modules/components/SliderItem.tsx
  src/renderer/modules/components/SwitchItem.tsx
  src/renderer/modules/components/Text.tsx
  src/renderer/modules/components/TextArea.tsx
  src/renderer/modules/components/TextInput.tsx
  src/renderer/modules/components/Tooltip.tsx
  src/types/coremods/message.ts
Labels: dependencies, semver: minor, types

#436 feat: addon watcher
  .eslintrc.yml
  bin/replugged.mjs
  package.json
  pnpm-lock.yaml
  src/main/ipc/i18n.ts
  src/renderer/coremods/installer/index.tsx
  src/renderer/coremods/rpc/index.ts
  src/renderer/coremods/settings/pages/Updater.tsx
  src/renderer/coremods/watcher/index.ts
  src/renderer/managers/coremods.ts
  src/renderer/managers/plugins.ts
  src/renderer/util.ts
  tsconfig.json
Labels: enhancement, semver: minor

#460 Add breadcrumb navigation for plugin settings
  src/renderer/coremods/settings/pages/Addons.tsx
Labels: enhancement, semver: minor

#462 fix(useSetting): support checkbox
  src/renderer/util.ts
Labels: bug, semver: patch

#435 Add dev companion coremod
  src/renderer/coremods/devCompanion/index.tsx
  src/renderer/coremods/settings/pages/General.tsx
Labels: enhancement, semver: minor

#449 feat: beginnings of context menu api
  cspell.json
  src/renderer/coremods/contextMenu/index.tsx
  src/renderer/coremods/contextMenu/plaintextPatches.ts
  src/renderer/managers/coremods.ts
  src/renderer/modules/common/contextMenu.ts
  src/renderer/modules/components/ContextMenu.tsx
  src/renderer/modules/injector.ts
  src/types/coremods/contextMenu.ts
  src/types/index.ts
Labels: enhancement, semver: minor
