Repository replugged-org/replugged, pull requests merged in 2023-03, with the labels that each got.

#422 feat: add notice and percentages in language settings
  cspell.json
  src/renderer/coremods/language/index.tsx
  src/renderer/coremods/language/plaintextPatches.ts
  src/renderer/managers/coremods.ts
  src/renderer/modules/components/FormNotice.tsx
  src/renderer/modules/components/index.ts
Labels: semver: minor

#423 feat: use electron types
  package.json
  pnpm-lock.yaml
  src/globals.d.ts
Labels: semver: patch

#420 fix(types): fix parser rule type
  src/renderer/modules/common/parser.ts
Labels: semver: patch

#425 fix: updater getting stuck if local version changes
  src/renderer/managers/updater.ts
Labels: semver: patch

#426 fix(common): injector not working on merged modules
  cspell.json
  src/renderer/modules/common/channels.ts
  src/renderer/modules/common/guilds.ts
  src/renderer/modules/common/messages.ts
  src/renderer/modules/common/users.ts
  src/renderer/util.ts
Labels: semver: patch

#419 feat: notify for new updates when using the addon CLI
  bin/replugged.mjs
  package.json
  pnpm-lock.yaml
Labels: semver: minor

#427 added /usr/lib as a known path
  scripts/inject/platforms/linux.ts
Labels: semver: patch

#429 fix(common): fix constants.CSSVariables
  src/renderer/modules/common/constants.ts
Labels: semver: patch

#433 fix: catch webpack errors
  src/renderer/modules/webpack.ts
Labels: semver: patch

#434 fix: apply log filtering to all logs
  src/renderer/modules/webpack.ts
Labels: semver: patch

#437 feat(types): common modules
  src/renderer/modules/common/api.ts
  src/renderer/modules/common/channels.ts
  src/renderer/modules/common/fluxDispatcher.ts
  src/renderer/modules/common/messages.ts
  src/renderer/modules/common/modal.ts
  src/renderer/modules/common/parser.ts
  src/renderer/modules/common/toast.ts
  src/renderer/modules/common/users.ts
Labels: semver: patch, types
