Repository replugged-org/replugged, pull requests merged in 2023-07, with the labels that each got.

#505 add welcome notice
  src/renderer/coremods/welcome/index.ts
  src/renderer/managers/coremods.ts
  src/types/settings.ts
Labels: enhancement, semver: minor

#506 fix: lock file version
  cspell.json
  pnpm-lock.yaml
  src/renderer/modules/common/constants.ts
  src/renderer/modules/common/flux.ts
  src/renderer/modules/common/messages.ts
  src/renderer/modules/common/parser.ts
  src/renderer/modules/common/users.ts
  src/renderer/modules/components/Text.tsx
Labels: bug, semver: patch, types

#508 feat: add i18n to dev companion settings
  src/renderer/coremods/settings/pages/General.tsx
Labels: enhancement, semver: patch

#502 Add timeout
  src/renderer/managers/plugins.ts
Labels: bug, semver: patch

#513 Fix last checked timestamp
  src/renderer/coremods/settings/pages/Updater.tsx
Labels: bug, semver: patch

#514 Improvements to install links
  src/renderer/coremods/installer/index.tsx
  src/renderer/coremods/installer/util.tsx
  src/renderer/coremods/settings/pages/Addons.tsx
Labels: enhancement, semver: minor

#521 Remove old eslint disable lines
  src/renderer/coremods/settings/pages/QuickCSS.tsx
Labels: semver: none

#522 feat(flux): add hooks and SnapshotStore
  src/renderer/modules/common/flux.ts
Labels: enhancement, semver: minor, addon development
