Repository replugged-org/replugged, pull requests merged in 2023-10, with the labels that each got.

#543 Call injected callbacks with the this keyword set
  src/renderer/modules/injector.ts
Labels: bug, semver: patch, addon development

#564 Separate dist for bundle
  .gitignore
  scripts/build.mts
Labels: bug, semver: none

#538 Fixes for Flatpak
  scripts/inject/injector.mts
Labels: bug, semver: none

#566 non store install bug fix
  src/main/ipc/installer.ts
Labels: bug, semver: patch

#551 Install Command
  src/renderer/coremods/installer/AddonEmbed.tsx
  src/renderer/coremods/installer/commands.ts
  src/renderer/coremods/installer/index.tsx
  src/renderer/coremods/installer/util.tsx
Labels: enhancement, semver: minor

#567 Fix command type import
  src/renderer/modules/injector.ts
Labels: bug, semver: patch, types

#559 Slash command api bug fix
  src/renderer/apis/commands.ts
  src/renderer/coremods/installer/index.tsx
  src/types/coremods/commands.ts
  src/types/discord.ts
Labels: bug, enhancement, semver: minor, addon development

#571 SliderItem margin fix and types
  src/main/ipc/settings.ts
  src/main/ipc/themes.ts
  src/renderer/modules/common/channels.ts
  src/renderer/modules/common/constants.ts
  src/renderer/modules/common/flux.ts
  src/renderer/modules/common/fluxDispatcher.ts
  src/renderer/modules/common/messages.ts
  src/renderer/modules/components/FormItem.tsx
  src/renderer/modules/components/Loader.tsx
  src/renderer/modules/components/Modal.tsx
  src/renderer/modules/components/RadioItem.tsx
  src/renderer/modules/components/SliderItem.tsx
Labels: bug, semver: patch, types
