Repository replugged-org/replugged, pull requests merged in 2023-06, with the labels that each got.

#463 feat(types): complete Modal, Text, Button popover and contextMenu
  src/renderer/apis/settings.ts
  src/renderer/coremods/contextMenu/index.tsx
  src/renderer/coremods/messagePopover/index.ts
  src/renderer/coremods/settings/pages/AddonSettings.tsx
  src/renderer/coremods/settings/pages/Addons.tsx
  src/renderer/modules/common/channels.ts
  src/renderer/modules/common/contextMenu.ts
  src/renderer/modules/common/flux.ts
  src/renderer/modules/common/guilds.ts
  src/renderer/modules/common/modal.ts
  src/renderer/modules/components/ButtonItem.tsx
  src/renderer/modules/components/Category.tsx
  src/renderer/modules/components/CheckboxItem.tsx
  src/renderer/modules/components/Clickable.tsx
  src/renderer/modules/components/ContextMenu.tsx
  src/renderer/modules/components/Divider.tsx
  src/renderer/modules/components/Flex.tsx
  src/renderer/modules/components/FormItem.tsx
  src/renderer/modules/components/FormNotice.tsx
  src/renderer/modules/components/FormText.tsx
  src/renderer/modules/components/Loader.tsx
  src/renderer/modules/components/Modal.tsx
  src/renderer/modules/components/Notice.tsx
  src/renderer/modules/components/RadioItem.tsx
  src/renderer/modules/components/SelectItem.tsx
  src/renderer/modules/components/SliderItem.tsx
  src/renderer/modules/components/SwitchItem.tsx
  src/renderer/modules/components/Text.tsx
  src/renderer/modules/components/TextArea.tsx
  src/renderer/modules/components/TextInput.tsx
  src/renderer/modules/components/Tooltip.tsx
  src/renderer/modules/injector.ts
  src/types/coremods/contextMenu.ts
  src/types/coremods/message.ts
  src/types/coremods/settings.ts
  tsconfig.json
Labels: semver: minor, types

#456 feat: support replugged store
  src/main/ipc/installer.ts
  src/main/ipc/settings.ts
  src/preload.ts
  src/renderer/coremods/installer/util.ts
  src/renderer/managers/updater.ts
  src/types/addon.ts
  src/types/installer.ts
Labels: enhancement, semver: minor

#471 fix(types): component icons
  src/renderer/modules/components/ContextMenu.tsx
  src/renderer/modules/components/RadioItem.tsx
  src/renderer/modules/injector.ts
  src/types/coremods/message.ts
Labels: bug, semver: patch, types

#467 Auto update checking
  src/renderer/apis/notices.ts
  src/renderer/coremods/notices/index.tsx
  src/renderer/coremods/notices/noticeMod.tsx
  src/renderer/coremods/settings/pages/Updater.css
  src/renderer/coremods/settings/pages/Updater.tsx
  src/renderer/managers/coremods.ts
  src/renderer/managers/ignition.ts
  src/renderer/managers/updater.ts
  src/renderer/util.ts
  src/types/index.ts
Labels: enhancement, semver: minor

#476 fix(types): addMenuItem raw type
  src/renderer/coremods/contextMenu/index.tsx
  src/renderer/modules/components/ContextMenu.tsx
  src/types/coremods/contextMenu.ts
Labels: semver: patch, types

#475 Add image and source keys
  src/types/addon.ts
Labels: enhancement, semver: minor, types

#477 feat: add dev mode warning
  src/renderer/coremods/settings/pages/Updater.tsx
Labels: enhancement, semver: patch

#468 i18n issue fix
  src/renderer/modules/i18n.ts
Labels: bug, semver: patch

#469 Load Quick CSS after themes
  src/renderer/managers/ignition.ts
Labels: bug, semver: patch

#479 Permission fix and other something
  package.json
  pnpm-lock.yaml
  scripts/inject/injector.mts
  src/util.mts
Labels: bug, semver: patch

#480 fix(notices): switched to plaintextPatches for the container injection
  src/renderer/coremods/notices/index.tsx
  src/renderer/coremods/notices/plaintextPatches.tsx
  src/renderer/managers/coremods.ts
Labels: bug, semver: patch

#483 feat(common): add moment.js
  package.json
  pnpm-lock.yaml
  src/renderer/modules/common/index.ts
  src/renderer/modules/common/lodash.ts
  src/renderer/modules/common/messages.ts
  src/renderer/modules/common/moment.ts
  src/renderer/modules/common/react-dom.ts
  src/renderer/modules/common/react.ts
  src/renderer/modules/components/ContextMenu.tsx
Labels: enhancement, dependencies, semver: minor, addon development

#478 feat(common): add more constants
  src/renderer/modules/common/constants.ts
Labels: enhancement, semver: minor, addon development

#492 Allow usage of the web rewrite for RPC commands
  src/renderer/coremods/rpc/index.ts
Labels: semver: patch

#490 Quick CSS auto reload
  src/renderer/coremods/settings/pages/General.tsx
  src/renderer/coremods/settings/pages/QuickCSS.tsx
  src/types/settings.ts
Labels: enhancement, semver: minor

#489 Updates to addon pages
  src/renderer/coremods/badges/badge.tsx
  src/renderer/coremods/installer/util.tsx
  src/renderer/coremods/settings/pages/Addons.tsx
  src/renderer/coremods/settings/pages/Updater.tsx
  src/renderer/util.ts
Labels: enhancement, semver: minor

#494 getByStoreName
  src/renderer/modules/webpack/helpers.ts
Labels: refactor, semver: patch, types

#500 fix(main): Fix `electron-devtools-installer` & Watch Together
  src/main/index.ts
Labels: bug, semver: patch

#495 context menu api fix
  src/renderer/coremods/contextMenu/plaintextPatches.ts
Labels: bug, semver: patch

#498 Fix ignition issues (for real this time hopefully)
  src/renderer/managers/ignition.ts
  src/renderer/modules/common/index.ts
  src/renderer/modules/components/index.ts
  src/renderer/modules/webpack/patch-load.ts
Labels: bug, semver: patch

#503 Package updates
  package.json
  pnpm-lock.yaml
Labels: semver: patch
