Repository replugged-org/replugged, pull requests merged in 2023-09, with the labels that each got.

#548 fix(openExternal): use correct module
  src/renderer/modules/common/channels.ts
  src/renderer/modules/components/Modal.tsx
  src/renderer/modules/components/Tooltip.tsx
  src/renderer/util.ts
Labels: bug, semver: patch, types

#547 Context Menu Components fix
  src/renderer/modules/components/ContextMenu.tsx
Labels: bug, semver: patch

#546 type error fix
  src/renderer/modules/components/RadioItem.tsx
Labels: bug, semver: patch, types

#501 Slash command api
  cspell.json
  pnpm-lock.yaml
  src/renderer/apis/commands.ts
  src/renderer/coremods/commands/commands.ts
  src/renderer/coremods/commands/index.ts
  src/renderer/coremods/commands/plaintextPatches.ts
  src/renderer/managers/coremods.ts
  src/renderer/modules/common/constants.ts
  src/renderer/modules/common/i18n.ts
  src/renderer/modules/common/messages.ts
  src/renderer/modules/injector.ts
  src/renderer/replugged.ts
  src/types/coremods/commands.ts
  src/types/discord.ts
  src/types/index.ts
  src/types/util.ts
Labels: enhancement, semver: minor, addon development

#560 Implement splash themes
  i18n/es-ES.json
  i18n/fi.json
  i18n/ja.json
  i18n/pl.json
  src/main/index.ts
  src/renderer/index.ts
  src/renderer/managers/ignition.ts
  src/renderer/managers/themes.ts
  src/renderer/modules/logger.ts
  src/types/addon.ts
Labels: enhancement, semver: minor

#561 Improve various logs
  src/renderer/managers/ignition.ts
  src/renderer/managers/plugins.ts
Labels: enhancement, semver: patch

#550 Support for monorepos
  bin/index.mts
  bin/mono.mts
  bin/release.mts
Labels: enhancement, semver: minor, addon development

#553 feat(ErrorBoundary): add error stack and plugin name
  src/renderer/modules/components/ErrorBoundary.css
  src/renderer/modules/components/ErrorBoundary.tsx
Labels: enhancement, semver: minor

#555 Support sub-imports from replugged package
  .gitignore
  bin/index.mts
  package.json
  scripts/create-import-wrappers.mts
Labels: enhancement, semver: minor, addon development
