Repository replugged-org/replugged, pull requests merged in 2024-04, with the labels that each got.

#607 fix: api module not found
  cspell.json
  src/globals.d.ts
  src/renderer/coremods/settings/pages/Addons.tsx
  src/renderer/modules/common/api.ts
  src/renderer/modules/common/lodash.ts
Labels: bug, semver: patch, types

#606 Handle extant but invalid potential discord install dirs
  scripts/inject/platforms/linux.mts
Labels: enhancement, semver: patch

#604 fixed slash command api
  cspell.json
  scripts/build.mts
  src/renderer/apis/commands.ts
  src/renderer/assets/assets.d.ts
  src/renderer/assets/logo.png
  src/renderer/coremods/commands/index.ts
Labels: bug, semver: patch

#596 fix(bin): fix esbuild.extra.mjs import path on Windows
  bin/index.mts
Labels: bug, semver: patch

#616 Allow specifying of injector entrypoint
  .github/workflows/cspell.yml
  .github/workflows/eslint.yml
  .github/workflows/prettier.yml
  .github/workflows/release.yml
  .github/workflows/typescript.yml
  cspell.json
  package.json
  pnpm-lock.yaml
  scripts/build.mts
  scripts/inject/checks/elevate.mts
  scripts/inject/checks/env.mts
  scripts/inject/index.mts
  scripts/inject/injector.mts
  scripts/inject/platforms/linux.mts
Labels: enhancement, refactor, dependencies
