Repository replugged-org/replugged, pull requests merged in 2024-06, with the labels that each got.

#623 refactor: badges coremod rewrite
  src/constants.ts
  src/main/ipc/installer.ts
  src/main/ipc/react-devtools.ts
  src/renderer/coremods/badges/badge.css
  src/renderer/coremods/badges/badge.tsx
  src/renderer/coremods/badges/badges/Booster.tsx
  src/renderer/coremods/badges/badges/BugHunter.tsx
  src/renderer/coremods/badges/badges/Contributor.tsx
  src/renderer/coremods/badges/badges/Developer.tsx
  src/renderer/coremods/badges/badges/EarlyUser.tsx
  src/renderer/coremods/badges/badges/Staff.tsx
  src/renderer/coremods/badges/badges/Support.tsx
  src/renderer/coremods/badges/badges/Translator.tsx
  src/renderer/coremods/badges/index.tsx
  src/renderer/coremods/badges/plaintextPatches.ts
  src/renderer/coremods/language/index.tsx
  src/renderer/coremods/rpc/index.ts
  src/renderer/coremods/settings/pages/General.tsx
  src/renderer/managers/coremods.ts
  src/types/discord.ts
  src/types/settings.ts
Labels: bug, refactor, semver: patch, types

#624 fix: missing key for the i18n contribute string
  src/constants.ts
  src/renderer/coremods/badges/index.tsx
  src/renderer/coremods/language/index.tsx
  src/renderer/coremods/welcome/index.ts
Labels: bug, semver: patch

#627 fix: notices coremod crash
  src/renderer/coremods/notices/noticeMod.tsx
Labels: bug, semver: patch

#622 feat(types): update modules
  cspell.json
  src/renderer/modules/common/fluxDispatcher.ts
  src/renderer/modules/common/messages.ts
  src/renderer/modules/components/ButtonItem.tsx
  src/renderer/modules/components/Clickable.tsx
  src/renderer/modules/components/FormItem.tsx
  src/renderer/modules/components/FormText.tsx
  src/renderer/modules/components/Loader.tsx
  src/renderer/modules/components/SwitchItem.tsx
  src/renderer/modules/components/Text.tsx
  src/renderer/modules/components/TextArea.tsx
  src/renderer/modules/components/TextInput.tsx
  src/renderer/modules/components/Tooltip.tsx
  src/types/coremods/contextMenu.ts
  src/types/discord.ts
Labels: semver: patch, types

#631 Fix for Discord re-enabling mangled exports
  package.json
  src/renderer/apis/commands.ts
  src/renderer/coremods/badges/index.tsx
  src/renderer/coremods/commands/index.ts
  src/renderer/coremods/contextMenu/index.tsx
  src/renderer/coremods/installer/index.tsx
  src/renderer/coremods/notices/noticeMod.tsx
  src/renderer/coremods/notrack/index.ts
  src/renderer/coremods/rpc/index.ts
  src/renderer/managers/coremods.ts
  src/renderer/modules/common/api.ts
  src/renderer/modules/common/constants.ts
  src/renderer/modules/common/flux.ts
  src/renderer/modules/common/fluxHooks.ts
  src/renderer/modules/common/index.ts
  src/renderer/modules/components/Notice.tsx
Labels: bug, semver: patch

#634 fix(scripts): catch and exit if building fails
  bin/index.mts
  scripts/build.mts
Labels: bug, semver: patch
