Repository replugged-org/replugged, pull requests merged in 2024-07, with the labels that each got.

#632 QuickCSS changes
  cspell.json
  src/renderer/coremods/settings/pages/QuickCSS.css
Labels: enhancement, semver: patch

#630 Dependencies updates
  .github/workflows/cspell.yml
  .github/workflows/eslint.yml
  .github/workflows/prettier.yml
  .github/workflows/release.yml
  .github/workflows/typescript.yml
  .nvmrc
  bin/index.mts
  package.json
  pnpm-lock.yaml
  scripts/build.mts
  src/main/ipc/installer.ts
  src/renderer/apis/settings.ts
  src/renderer/coremods/commands/commands.ts
  src/renderer/coremods/settings/pages/Updater.tsx
  src/renderer/modules/common/hljs.ts
  src/renderer/modules/common/index.ts
  src/renderer/util.ts
Labels: dependencies

#637 fix: badges on the new profile design
  src/renderer/coremods/badges/index.tsx
  src/renderer/coremods/badges/plaintextPatches.ts
Labels: bug, semver: patch

#636 Fix crashes
  cspell.json
  src/renderer/coremods/language/plaintextPatches.ts
  src/renderer/coremods/messagePopover/plaintextPatches.ts
  src/renderer/coremods/notices/plaintextPatches.tsx
  src/renderer/coremods/settings/plaintextPatches.ts
  src/renderer/index.ts
  src/renderer/managers/coremods.ts
  src/renderer/managers/ignition.ts
  src/renderer/managers/plugins.ts
  src/renderer/modules/i18n.ts
  src/renderer/modules/webpack/patch-load.ts
  src/types/webpack.ts
Labels: bug, semver: patch

#614 slash command ephemeral message fix
  src/constants.ts
  src/renderer/apis/commands.ts
  src/renderer/coremods/commands/index.ts
Labels: bug, semver: patch

#638 fix splash theming
  bin/index.mts
Labels: bug, semver: patch
