Repository replugged-org/replugged, pull requests merged in 2025-02, with the labels that each got.

#664 Components fix
  cspell.json
  src/renderer/coremods/contextMenu/index.tsx
  src/renderer/coremods/contextMenu/plaintextPatches.ts
  src/renderer/modules/common/components.ts
  src/renderer/modules/components/ButtonItem.tsx
  src/renderer/modules/components/Category.tsx
  src/renderer/modules/components/CheckboxItem.tsx
  src/renderer/modules/components/Clickable.tsx
  src/renderer/modules/components/ContextMenu.tsx
  src/renderer/modules/components/Divider.tsx
  src/renderer/modules/components/Flex.tsx
  src/renderer/modules/components/FormItem.tsx
  src/renderer/modules/components/FormNotice.tsx
  src/renderer/modules/components/FormText.tsx
  src/renderer/modules/components/Loader.tsx
  src/renderer/modules/components/Modal.tsx
  src/renderer/modules/components/Notice.tsx
  src/renderer/modules/components/RadioItem.tsx
  src/renderer/modules/components/SelectItem.tsx
  src/renderer/modules/components/SliderItem.tsx
  src/renderer/modules/components/SwitchItem.tsx
  src/renderer/modules/components/TextArea.tsx
  src/renderer/modules/components/TextInput.tsx
  src/renderer/modules/components/Tooltip.tsx
Labels: bug, semver: patch

#663 feat: disable sentry
  src/main/index.ts
  src/renderer/coremods/notrack/index.ts
  src/renderer/managers/coremods.ts
Labels: enhancement, semver: patch

#660 rdtComponentSourceFix
  src/globals.d.ts
  src/renderer/coremods/rdtComponentSourceFix/index.ts
  src/renderer/managers/coremods.ts
Labels: bug, semver: patch

#665 fix: notice having undefined components
  src/renderer/coremods/notices/noticeMod.tsx
Labels: bug, semver: patch

#666 RPC Coremod Fix
  src/renderer/coremods/rpc/index.ts
Labels: bug, semver: patch

#670 Context Menu API PlaintextPatch
  src/renderer/coremods/contextMenu/plaintextPatches.ts
Labels: bug, semver: patch

#517 Auto relaunch
  scripts/inject/index.mts
  scripts/inject/injector.mts
  scripts/inject/types.mts
  scripts/inject/util.mts
Labels: enhancement, semver: none
