Repository replugged-org/replugged, pull requests merged in 2025-06, with the labels that each got.

#695 Copy logo as file instead of data url
  scripts/build.mts
  src/main/index.ts
Labels: refactor, semver: patch

#669 Add localStorage
  src/renderer/modules/common/index.ts
  src/renderer/modules/common/localStorage.ts
Labels: enhancement, semver: minor

#698 fix: simplify preload script handling
  src/main/index.ts
Labels: bug, semver: patch

#699 Allow Media
  src/main/index.ts
Labels: enhancement, semver: patch
