Repository replugged-org/replugged, pull requests merged in 2025-04, with the labels that each got.

#676 fix(messagePopover): HoverBarButton being undefined
  eslint.config.mjs
  src/renderer/coremods/messagePopover/index.tsx
Labels: bug, semver: patch

#679 Remove import default as
  src/renderer/managers/coremods.ts
Labels: semver: none

#680 feat: add support for desktop visual refresh
  src/renderer/coremods/notices/index.tsx
  src/renderer/coremods/notices/plaintextPatches.ts
  src/renderer/coremods/settings/pages/Addons.css
  src/renderer/coremods/settings/pages/Updater.css
  src/renderer/coremods/settings/pages/Updater.tsx
Labels: enhancement, semver: patch

#678 fix: ignition failing
  bin/index.mts
  i18n/en-US.messages.d.ts
  package.json
  pnpm-lock.yaml
  scripts/build-plugins/intl-loader.mts
  scripts/build-plugins/intl-type-generator.mts
  scripts/build-plugins/log-build.mts
  scripts/build-plugins/pre-bundle.mts
  scripts/build.mts
  scripts/inject/index.mts
  src/main/index.ts
  src/main/ipc/index.ts
  src/main/ipc/installer.ts
  src/main/ipc/plugins.ts
  src/main/ipc/react-devtools.ts
  src/main/ipc/settings.ts
  src/preload.ts
  src/renderer/apis/settings.ts
  src/renderer/coremods/badges/plaintextPatches.ts
  src/renderer/coremods/experiments/plaintextPatches.ts
  src/renderer/coremods/installer/util.tsx
  src/renderer/coremods/language/index.tsx
  src/renderer/coremods/notrack/plaintextPatches.ts
  src/renderer/coremods/rpc/index.ts
  src/renderer/coremods/settings/pages/Addons.tsx
  src/renderer/coremods/settings/pages/General.tsx
  src/renderer/coremods/settings/pages/QuickCSS.tsx
  src/renderer/index.ts
  src/renderer/managers/ignition.ts
  src/renderer/managers/plugins.ts
  src/renderer/managers/themes.ts
  src/renderer/managers/updater.ts
  src/renderer/modules/common/components.ts
  src/renderer/modules/common/i18n.ts
  src/renderer/modules/common/index.ts
  src/renderer/modules/common/typing.ts
  src/renderer/modules/components/Notice.tsx
  src/renderer/modules/i18n.ts
  src/renderer/modules/webpack/helpers.ts
  src/renderer/modules/webpack/patch-load.ts
  src/renderer/util.ts
  src/types/index.ts
  src/types/settings.ts
  src/util.mts
Labels: bug, refactor, semver: patch

#681 fix(bin): wrong module import
  bin/index.mts
Labels: bug, semver: patch

#682 fix: update IPC version retrieval to use synchronous method
  src/main/ipc/installer.ts
  src/preload.ts
Labels: bug, semver: patch

#633 Slash Command Reply
  src/renderer/apis/commands.ts
  src/renderer/modules/common/messages.ts
Labels: enhancement, semver: patch

#683 feat: popout theming
  src/renderer/coremods/popoutTheming/plaintextPatches.ts
  src/renderer/managers/coremods.ts
Labels: enhancement, semver: minor

#644 custom titlebar on linux
  cspell.json
  i18n/en-US.messages.d.ts
  i18n/en-US.messages.js
  src/globals.d.ts
  src/main/index.ts
  src/renderer/coremods/settings/pages/General.tsx
  src/renderer/coremods/titleBar/plaintextPatches.ts
  src/renderer/managers/coremods.ts
  src/types/settings.ts
  tsconfig.json
Labels: enhancement, semver: minor

#684 fix: commands
  src/renderer/coremods/commands/index.ts
Labels: bug, semver: patch

#687 Fix Quick CSS editor overflowing the page on Windows
  src/renderer/coremods/settings/pages/QuickCSS.css
Labels: bug, semver: patch
